[[LLVMBootstrap]]
arch = "x86_64"
git-tree-sha1 = "15fc44968ddfde74f5a185a76218f448fb4bf9f4"
libc = "musl"
os = "linux"

    [[LLVMBootstrap.download]]
    sha256 = "ee559d28ef7bb5f76fd860d53f1b76ab030bbe95c932f276707b6736a1111b71"
    url = "https://github.com/JuliaBinaryWrappers/LLVMBootstrap_jll.jl/releases/download/LLVMBootstrap-v7.1.0+0/LLVMBootstrap.v7.1.0.x86_64-linux-musl.tar.gz"
